imports:
    - { resource: "@BitBagSyliusWishlistPlugin/Resources/config/services.yml" }
    - { resource: "@BitBagSyliusWishlistPlugin/Resources/config/resources.yml" }

sylius_ui:
    events:
        sylius.admin.layout.javascripts:
            blocks:
                version_script:
                    template: "@BitBagSyliusWishlistPlugin/Asset/_versionScript.html.twig"
                    priority: 30
